version: '3.9'
services:
  node:
    image: node
    working_dir: /home/node/app
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm run dev'
    ports:
      - '5173:5173'
    volumes:
      - './vue-project:/home/node/app'
