/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCard: typeof import('./src/components/addCard/AddCard.vue')['default']
    BackCardTemplate: typeof import('./src/components/addCard/BackCardTemplate.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormFile: typeof import('bootstrap-vue-next')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFOrmGroup: typeof import('bootstrap-vue-next')['BFOrmGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    ButtonPdf: typeof import('./src/components/addCard/ButtonPdf.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardTemplate: typeof import('./src/components/addCard/CardTemplate.vue')['default']
    CreatePdf: typeof import('./src/components/addCard/CreatePdf.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Onboarding: typeof import('./src/components/addCard/Onboarding.vue')['default']
    OnboardingAdd: typeof import('./src/components/addCard/OnboardingAdd.vue')['default']
    OnboardingAddCard: typeof import('./src/components/addCard/OnboardingAddCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
