/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCard: typeof import('./src/components/addCard/AddCard.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormFile: typeof import('bootstrap-vue-next')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CardBrand: typeof import('./src/components/addCard/CardBrand.vue')['default']
    CardTemplate: typeof import('./src/components/addCard/CardTemplate.vue')['default']
    CountComponent: typeof import('./src/components/versus/CountComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    GenerateBrand: typeof import('./src/components/versus/GenerateBrand.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    OnboardingAddCard: typeof import('./src/components/addCard/OnboardingAddCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
